// <auto-generated />
using System;
using System.Text.Json;
using FormR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormR.Data.Migrations
{
    [DbContext(typeof(FormBuilderContext))]
    [Migration("20260117215937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormR.Core.Models.ControlLibrary", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ConfigSchema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("DefaultProps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Type");

                    b.ToTable("ControlLibrary");
                });

            modelBuilder.Entity("FormR.Core.Models.FormControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentControlId")
                        .HasColumnType("uuid");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<JsonDocument>("Position")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ValidationRules")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ParentControlId");

                    b.HasIndex("TemplateId");

                    b.ToTable("FormControls");
                });

            modelBuilder.Entity("FormR.Core.Models.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseTemplateId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "Version", "TenantId")
                        .IsUnique();

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("FormR.Core.Models.FormControl", b =>
                {
                    b.HasOne("FormR.Core.Models.FormControl", "ParentControl")
                        .WithMany("ChildControls")
                        .HasForeignKey("ParentControlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FormR.Core.Models.FormTemplate", "Template")
                        .WithMany("Controls")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentControl");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormR.Core.Models.FormTemplate", b =>
                {
                    b.HasOne("FormR.Core.Models.FormTemplate", "BaseTemplate")
                        .WithMany("DerivedTemplates")
                        .HasForeignKey("BaseTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseTemplate");
                });

            modelBuilder.Entity("FormR.Core.Models.FormControl", b =>
                {
                    b.Navigation("ChildControls");
                });

            modelBuilder.Entity("FormR.Core.Models.FormTemplate", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("DerivedTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
